### PR TITLE
Adds psalm and fixes first few findings

### PR DESCRIPTION
**Pull request by NielsdeBlaauw**

### CODE REVIEW

**Comment by menno-ll** [comment]
psalm requires php 7.1 >=
We currently only define php 7.0 >=, so there is a change of errors occuring

**Comment by menno-ll** [comment]
In the composer test script, testing with psalm takes a long time. We can make it faster for example if we only check changed files. maybe we should consider that. See command options with `/vendor/bin/psalm --help` or https://github.com/vimeo/psalm/blob/master/docs/running_psalm/command_line_usage.md

**Comment by menno-ll** [comment]
We can consider automatic fixing just like phpcbf that they have built in. 

see https://github.com/vimeo/psalm/blob/master/docs/manipulating_code/fixing.md

**Comment by NielsdeBlaauw** [comment]
> psalm requires php 7.1 >=
> We currently only define php 7.0 >=, so there is a change of errors occuring
> 
> see https://github.com/vimeo/psalm/blob/master/docs/running_psalm/installation.md

Versie van psalm die we hier gebruiken v3.2.12. Die zou nog wel compatible moeten zijn met 7.0, maar gezien de wijzigingen met de #152 kunnen we van 7.1 uitgaan.

**Comment by NielsdeBlaauw** [comment]
> We can consider automatic fixing just like phpcbf that they have built in.

Risky for now. Let's make a ticket and explore this later.

**Pull request merged**
